app:
  env: development
  debug: true

postgres:
  dsn: "host=localhost user=postgres password=password dbname=golang_sample port=5432 sslmode=disable"

api:
  secret: "test-jwt-secret-key-for-testing-purposes-only"
