[tools]
go = "1.25.5"
"go:github.com/heyvito/go-oif/cmd/go-oif" = "latest"
"go:github.com/google/wire/cmd/wire" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
golangci-lint = "latest"
mockery = "latest"
swag = "latest"

"pre-commit" = "latest"

"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"

